[package]
name = "holly"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
sdl3 = { version = "0.14.32", features = ["build-from-source-static", "static-link"] }
thiserror = "2.0.12"
